HOST: http://www.google.com/

--- Testing APIxooxox ---

Crate *user*
POST /user/{id}
< 201
< Content-Type: application/json
{
    "id": 2262625
}

GET /user/{id}
> Accept: application/json
< 200
< Content-Type: application/json
{
    "id": 2262625
}

GET /test
< 200





GET /test
< 200

