--- Github Sync test ---

---
Welcome to the our sample API documentation. All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)
---

Get applications blocked by firewall on given server. xoxo. testing. if. worky. 
GET /blacklists
< 200
< Content-Type: application/json
{
    "ips" : ["10.10.10.12", "213.4/16"],
    "applications" : [{"name": "torrent", "WindowsRegister" : "0xAA"}]
}

Save new products in your shopping cart
POST /shopping-cart
> Content-Type: application/json
{ "product":"1AB23ORM", "quantity": 2 }
< 201
< Content-Type: application/json
{ "status": "created", "url": "/shopping-cart/2" }

-- Payment Resources --

This resource allows you to submit payment information to process your *shopping cart* items
POST /payment
{ "cc": "12345678900", "cvc": "123", "expiry": "0112" }
< 200
{ "receipt": "/payment/receipt/1" }



GET /test
< 200





GET /test
< 200

